### ISSUE TITLE
Date picker editing functionality

### ISSUE THREAD

**Issue by Osmo123** [ghiscoding/Angular-Slickgrid#166]
**Need to edit and clear the date in the grid**
**Need urgent help**

* **Angular Version:**
major.minor.patch

* **Library Version:**
major.minor.patch

* **Browser:**
all

* **Language:**
TypeScript X.X

**Current behavior: It is not allowing us to clear the date in start and finish dates**

**Expected/desired behavior: Need to edit the date and clear the date in the grid**

* **What is the expected behavior?**
Allow to clear the date by clicking on backspace or provide any cross Icon to clear the date
Below is the code. Please help us how to clear the date in the grid
 {
        id: 'StartDate',
        name: 'Start Date ',
        field: 'StartDate',
        minWidth: 130,
        formatter: customDateFormatter,
        exportWithFormatter: true,
        sortable: true,
        type: FieldType.dateUsShort,
        editor: {
          model: Editors.date,
        },
        onCellChange: (e: Event, args: OnEventArgs) => this.checkAndPushIndexToEditArray(e, args)
      },

* **What is the motivation / use case for changing the behavior?**

**Comment by Osmo123** [comment]
Is it possible to do with editorOptions ? I checked in faltpickr its clearing the date by clicking the backspace.
Could you please let me know how we can clear the date by using editor options in the grid.

**Comment by ghiscoding** [comment]
As I mentioned earlier, you can pass any of the `Flatpickr` option to the editor, see this [line](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-editor.component.ts#L267) of the Editor Example.

**Comment by Osmo123** [comment]
As I checked with Flatpickr it is allowing as to clear the date by clicking the backspace.But after adding it to slickgrid it is not allowing us to clear the date.
Below is the link for your reference of flatpickr code
https://stackblitz.com/edit/angular-flatpickr.

In slickgrid I checked in Editor module its not allowing us to clear the date 
![image](https://user-images.githubusercontent.com/40761775/56290926-d4a71900-6141-11e9-878f-818935320c9c.png)

I tried with the editorOptions as well its not working.Please check and let us know

**Comment by ghiscoding** [comment]
You could try to help and troubleshoot the library yourself, the Date Editor is this [file](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/editors/dateEditor.ts).

**Comment by ghiscoding** [comment]
I fixed the issue in latest PR #166 and I will merge and push a new version in the coming days.

**Comment by ghiscoding** [comment]
This is now available under version `2.5.1` on [NPM](https://www.npmjs.com/package/angular-slickgrid).
The [demo](https://ghiscoding.github.io/Angular-Slickgrid/#/editor) was also updated and it works with backspace now

**Comment by BerndMinet** [comment]
Thanks, the backspace now removes the chosen value, but does not clear the filter -> "No data to display"
Only Clear all filters helps.

**Comment by BerndMinet** [comment]
I still have another problem with filtering a date column, can someone help?
![grafik](https://github.com/ghiscoding/Angular-Slickgrid/assets/114732775/dbeaf867-b9ab-41d1-9967-1eaa4632676a)

After selecting a date value the input field shows the number value of the date.
I tried with filterOptions set to:
dateFormat: 'DD.MM.YYYY HH:mm:ss'
but this did not help. Any idea?

**Comment by BerndMinet** [comment]
I found it: formatDate was the solution
