### ISSUE TITLE
Angular-Slickgrid Leaks Detached DOM Elements

### ISSUE THREAD

**Issue by tannenbaums** [ghiscoding/Angular-Slickgrid#625]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 10.2.1        | 
| Angular-Slickgrid   | 2.23.0        | 
| TypeScript              | 4.0.5        | 

### Describe the Bug
If you open up the Angular-Slickgrid sample app you will see that the DOM Nodes Section grows by a-lot, every click.
In my application I have a problem that after toggling between components that contain the grid a few times, typing speed gets very slow. I now believe that this is due to the DOM leak. If I remove the grid from the component (but leave the rest of the functionality) and toggle a few times, typing remains fast!!

### Steps to Reproduce
Open the Angular-Slickgrid sample app. Hit F12 to bring up Chrome Dev Tools, and take a look at the DOM Nodes count found in the Performance monitor (if you don't see it, just hit the 3 dots on the top right corner of the dev tools go to More Tools and Performance monitor). by me the count is just about 900 when loading the app.
Now keep on toggling between the examples, while watching the DOM Nodes. Notice it jumps by almost 2k almost every click
after about 10 clicks you are up to just below 20k, as below.

![image](https://user-images.githubusercontent.com/38888997/98179794-a036b180-1ecd-11eb-94b9-ee10591c6677.png)

Now, go ahead and head over to the memory tab. Hit the Take Snapshot button. Once loaded enter: Detached and you'll see a very large number of all sorts of detached Dom elements. The detached DOM elements are the cause for DOM leaks because they never get cleaned up. In the possible solution section I have a link to an article that shows a sample code solution.

### Expected Behavior
Dom Nodes should not grow at all, at-least not to this extent

### Current Behavior
My application gets sluggish after moving around from component to component (which almost all of them use the slick-grid)
the users are complaining that typing gets very slow.

### Possible Solution
This is probably because Angular-Slickgrid is using jquery internally. If not cleaned properly it can lead to this issue.
Please refer to this article:
https://www.toptal.com/angular-js/top-18-most-common-angularjs-developer-mistakes
go to number 10, with special focus on reason 3.

### Code Sample
No need, just use the Angular-slickgrid sample

**Comment by ghiscoding** [comment]
I don't know what else to do, I spent enough time on the leak. If you find something else then please make a PR, else I just don't have time and energy to work on this. Sorry.

**Comment by ghiscoding** [comment]
You can try again the grid dispose `this.angularGrid.destroy();` with `ngDestroy()` and see if that helps. I can't help more than that.

**Comment by tannenbaums** [comment]
I tried that, made no difference. And I was able to reproduce the typing slowness in the Angular-Slickgrid sample code. If I move around the components a bunch of times, the input boxes (such as column filters) starts getting slow (meaning there's a delay in the typing). In a big app with thousands of rows it adds up a lot quicker, because each cell is another detached html element.... Just to make things clear: In the sample code, every time the grid is destroyed, it leaves behind about 1700 orphaned (or detached) HTML Elements that are never going to get cleaned up. And this is caused by using jquery. I'm going to try and look at the code, but it means I'll have to spend time learning how it works. The memory leak in the previous issue is small compared to this one. If you follow my instructions you'll see very clearly a very big leak.

**Comment by ghiscoding** [comment]
It's very hard to help unless we can get to know what those orphan elements are. jQuery is used extensively in the core lib (SlickGrid) and in Angular-Slickgrid for a few of the Filters/Editors. The article you sent was written for AngularJS, so it's very hard to know what to do to fix this. If I try to understand the article, some of the leaks might be coming from the use of `.empty()` or `.remove()`? I'm not fully sure, I don't fully understand but anyway there are a few empty/remove in Angular-Slickgrid and in SlickGrid itself. 

I do see that Performance monitor window but it's just monitoring without any references to these orphan so it's not very helpful. But if I disable filtering in 2 of the Angular-Slickgrid examples and toggle a few times between the 2, I can still see the number increasing, so it might be coming from core SlickGrid itself but again it's very hard to troubleshoot since there's no references to look at.

**Comment by tannenbaums** [comment]
Thank you for your response! As I wrote in the bug report, if you want to see the actual objects, you can see it by taking a heap sample and then put the word detach in the search box, this will give you all of these orphaned objects and you can drill into them and look for strings that the application is putting in, etc. 
Actually, you are right, it seems like Slickgrid itself is leaking. When I play with example #1 and move the slidebar back and forth I can see the same exact effect, the nodes count grow a-lot. I guess I should submit a bug report there, but I'm not sure if he will respond. I don't think there's much activity going on there...

**Comment by ghiscoding** [comment]
I am the biggest contributor to the core lib for the past couple years, so if you write it here or on that fork I'll see both messages. I'm not sure which Example you're referring too but I'm not using all the same jQueryUI controls as the core SlickGrid, I have different sets of controls especially for the Editors/Filters. I think the slider you talk about is a jQueryUI Slider for the filter. The SlickGrid with the most features is the [Example 4](http://6pac.github.io/SlickGrid/examples/example4-model.html) and moving the slider a few times does eventually get lower, the mean difference with Angular-Slickgrid though is that we are in a SPA so we can't destroy the entire DOM. Also the thing to know about SlickGrid is that it only creates <div> elements for the rows that are shown to the user (with some buffer top/bottom) and every time you scroll it will remove previous and create new elements, that's called virtual scrolling (if you have 1 million rows, you don't want 1 million divs created because your HTML will be extremely slow and that is what makes SlickGrid extremely fast too), I believe these elements are destroyed properly but who knows really, it does seems ok to me (same Example 4, just playing with the slider filter and then stop)

![image](https://user-images.githubusercontent.com/643976/98289169-cca60880-1f75-11eb-8b35-c522d7255392.png)

**Comment by tannenbaums** [comment]
Yes I see that, in example 5 for example, it grows till 20k and then it goes down to 500. So than it must be something in the Angular-Slickgrid or just the fact that it's angular on top of jquery causes this issue. I don't know. I do know that this is a show-stopper for us. Not sure what to do!

**Comment by ghiscoding** [comment]
I would think it's maybe due to the fact that it's a SPA (Single Page App) and if you stay in the same page (Example) and you just play with the Filters or local Pagination, it doesn't grow much and goes down. The problem really seem to occur when leaving the page. I haven't used Angular-Slickgrid in past couple months and I'm now working mostly on [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal) that we use in Salesforce, this lib will eventually be used by Angular-Slickgrid, and I see the same problem too when toggling between Examples and in that lib I do call the `.dispose()` when leaving each Example page and that doesn't help either but I still think the issue is around the SPA. If you can give me a list of the orphan DOM elements, then I can troubleshoot a bit more but without that it's too hard to know. Most of the div created by SlickGrid start with the word `.slick-xyz`

**Comment by ghiscoding** [comment]
So I read couple of SO Q/A ([here](https://stackoverflow.com/questions/16901759/javascript-memory-leaks-detached-dom-tree), [here](https://stackoverflow.com/questions/21226646/locating-detached-dom-tree-memory-leak)) and tried couple of things and I think I'm on to something. Note that this is with Slickgrid-Universal not Angular-Slickgrid but it should be fairly similar, I disabled all features in the gridOptions because I want to see just the bundle itself to see if it leaks so I disabled most options like this:

```ts
this.gridOptions1 = {
      enableAutoResize: false,
      enableFiltering: false,
      enableGridMenu: false,
      enableHeaderMenu: false,
      enableColumnPicker: false,
      enableContextMenu: false,
      enableExport: false,
      enableColumnReorder: false,
      enableSorting: false,
    }
```

and when I dispose of the lib (that is the dispose of the lib itself, so in Angular-Slickgrid that would be this [destroy method](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts#L274)))
```ts
dispose() {
     // dispose the Services
    this.extensionService?.dispose();
    this.filterService?.dispose();
    // ...

    this.slickGrid?.destroy();

    // try adding a bunch of nulls since that seems to be what garbage collector wants and it seems to help
    this.dataView.setItems([]);
    this._gridOptions = null;
    this.slickGrid = null;
    this.dataView = null;
    this.sharedService = null;
    emptyElement(this._gridContainerElm);
    emptyElement(this._gridParentContainerElm);
    this._gridContainerElm = null;
    this._gridParentContainerElm = null;
```

I toggled between 2 Examples back and forth about 15-20 times, wait few seconds and it finally comes down, it seems I'm on to something :)

I didn't try in Angular-Sclickgrid lib itself, you could give that a try. I need to leave now but maybe next step is to re-enable some of the grid options to see if it still gets collected or not, if not then at least I can start pinpointing which option (plugin) would leak. That was a bit over 10k down to below 1k or 2k depending if I have 1 or 2 grids in the page.

![image](https://user-images.githubusercontent.com/643976/98306650-3c29f100-1f92-11eb-9bf0-dc0adf352205.png)

**Comment by tannenbaums** [comment]
Yup I see that.
Here are my grid options:

`this.gridOptions = {
      autoResize: {
        containerId: 'demo-container'
      },
      rowHeight: 60,
      enableRowSelection: true,
      enableCellNavigation: true,
      enableColumnPicker: true,
      enableExcelCopyBuffer: false,
      enableFiltering: false,
      enableAutoResize: true,
      forceFitColumns: true,
      i18n: this.translate,
    };`

If I set enableExcelCopyBuffer or enableFiltering to true, my typing gets very slow, otherwise i'm fine!

**Comment by ghiscoding** [comment]
Well actually that `enableExcelCopyBuffer` is this [Example - Excel Copy](https://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet.html) and I almost never use it because it conflicts with Row Selection (you cannot use both plugins because both require to use the `rowSelectionModel` and you can only create 1 instance, so again I almost never use it for that reason). I'm not sure if I've set the `enableExcelCopyBuffer` to true in the Global Grid Options but if it is then I'll turn it off because it's too problematic and if you think that is the one that leaks then there's more reason to disable it by default. 

Basically just to reiterate, the test that I did was to disable as much plugins as possible to have a naked grid (so to speak) and at first it was still growing in size, then after changing the lib code as I wrote earlier with a bunch of `null` in the dispose method it started to go down. I'll do some more tests tomorrow by enabling plugins 1 by 1 and see if it still goes down or not, at least it's a good starting point. 

Also the `enableFiltering: false` won't create any of the Filters (which were all created by me) and they might be part of the problem because I am not doing any `null` when destroying them yet. Also that [SO Answer](https://stackoverflow.com/a/16936890/1212166) says to

> c. Try not to use DOM references inside closures/inline handlers, instead pass identifiers

which I'm actually doing in nearly all my Filters (most use jQuery), so it might be a problem, I'll have to see.

> If I set enableExcelCopyBuffer or enableFiltering to true

I don't know what computer you use (or tablet/mobile?) but I never had that kind of issues, however I'm not dealing with extremely big grids (less than 15 columns and I typically use backend services because we deal with few thousands rows, so I rarely use local in-memory grids) and I also don't switch pages that often either so I never notice that kind of issues.

**Comment by ghiscoding** [comment]
@tannenbaums 
Here's the first pass to some of the changes I mentioned earlier, it doesn't fix everything but it should certainly help. Note that I'm still testing in my other lib Slickgrid-Universal and so far what I found is that the code change from that PR does help and I think the Filters (possible the Editors too) are now nearly all fixed but it seems that some of the plugins are still leaking. 

So to make it brief, the grid options I had earlier, I leave all plugins disable and only re-enable the `enableFiltering: true` and it seems to be all good (goes up and then goes back down after few seconds) but as soon as I re-enable all plugins then the problem is still visible
```ts
this.gridOptions1 = {
      enableAutoResize: false,
      enableFiltering: true, // re-enable it 
      enableGridMenu: false,
      enableHeaderMenu: false,
      enableColumnPicker: false,
      enableContextMenu: false,
      enableExport: false,
      enableColumnReorder: false,
      enableSorting: false,
}
```
I suggest that you give it a try, and if you want to try with your own code then do a build of the lib (with `yarn run build`) and take the `dist` content then overwrite your `/node_modules/angular-slickgrid/` folder. The lib is now using Angular 8, so you won't get the build error from last time which were occurring because of Angular 7.

I don't have more time to spend on this, so we'll have to start with that, it should definitely help.
Please provide feedback

**Comment by tannenbaums** [comment]
Hi,

Wow, this is very exciting, I can't wait to test it. I have to see if I'm able to do it without an official release. I'm leaving early today but I'll do it next week.

Thank you so much!!!

**Comment by ghiscoding** [comment]
I can merge the PR if that helps

**Comment by tannenbaums** [comment]
Yes very much so, ty!

**Comment by tannenbaums** [comment]
Wait what I thought you meant was that you'll merge and do a release, otherwise I don't know how to include it in my code.
I'm not sure though, it might be too early to do a release, because I am using the filters in my app and I thought you said that's still needs to be fixed. Also: I'm looking back at your other comment you wanted to know what we use: we are using regular desktop pc's. Windows 8, nothing fancy. The data is typically few thousands rows. I'm leaving now, I'll take a look next week. Have a great weekend!

**Comment by ghiscoding** [comment]
No I won't do a release, you should re-read what I wrote earlier...

> I suggest that you give it a try, and if you want to try with your own code then do a build of the lib (with yarn run build) and take the dist content then overwrite your /node_modules/angular-slickgrid/ folder. The lib is now using Angular 8, so you won't get the build error from last time which were occurring because of Angular 7.

**Comment by ghiscoding** [comment]
It seems that Flatpickr (date picker) might be leaking (see [issue](https://github.com/flatpickr/flatpickr/issues/1908)) and might be the cause of a few detached DOM elements. I can see a bunch showing up after running a memory snapshot and checking a few detached elements (also note that I went to a page that has no grid and therefore shouldn't have any flatpickr elements as leftover).

I think I found it, it was really Flatpickr as it was mentioned in that [issue](https://github.com/flatpickr/flatpickr/issues/1908) and I resolved it by using the code that I wrote in that same issue [here](https://github.com/flatpickr/flatpickr/issues/1908#issuecomment-723310900) and I no longer have Flatpickr leaking detached elements and it goes down to normal (at least in Slickgrid-Universal). It seems that jQuery is still leaking slightly though but hey I went down from 200 detached elements to 2, so not bad at all. 

So this 2nd [PR #627](https://github.com/ghiscoding/Angular-Slickgrid/pull/627) fixes the Flatpickr leak, that should help quite  a lot since it was leaving a lot of detached elements behind.

**Comment by tannenbaums** [comment]
Wow that sounds really good! any way I can have an Angular-Slickgrid release so I can test it in my app?

**Comment by tannenbaums** [comment]
Oh sorry, I just so your earlier comments. Ok np I will try it tomorrow with yarn and all. tysm!

**Comment by tannenbaums** [comment]
I see that you updated slick grid core. Does the latest angular-slickgrid with the examples contain the fixes to slickgrid?

**Comment by ghiscoding** [comment]
You'll need both changes, I saw that after changing about 15 times (pages), I am still left with 2 detached div (don't know how to get rid of them) and no more span but I still see some internal detached elements. So down from a over 500 (closer to 1000) to 2 is an improvement, however I still see a certain amount of detached doms. Anyhow, it should hopefully improve speed and leak less than before, Flatpickr was also a big leaker which I managed to patch a fix internally until they fix it on their side... So if you want to test it all, you'll have to run a build and also get the changes from the core lib for you to see all changes applied.

**Comment by tannenbaums** [comment]
I don't really know how to do that. Is it possible for you to share a zip file that has all that so I can just put it into my node_modules?

**Comment by ghiscoding** [comment]
- [slickgrid.zip](https://github.com/ghiscoding/Angular-Slickgrid/files/5511796/slickgrid.zip)
   - `/node_modules/slickgrid/`
- [angular-slickgrid-dist.zip](https://github.com/ghiscoding/Angular-Slickgrid/files/5511799/angular-slickgrid-dist.zip)
   - `/node_modules/angular-slickgrid/`

**Comment by ghiscoding** [comment]
There still seems to be some detached elements but I believe that it's much better than before. 
I think that is the best I can do and that requires the core lib PR to be merged and released as well as all the PRs I made here too, the 2 zips has all of the changes.

**Comment by tannenbaums** [comment]
Thank you so much for that! So now when I try to enter the page I get the error below, looks like _selector is null:

![image](https://user-images.githubusercontent.com/38888997/98580969-cd4ce080-228e-11eb-9848-7e8846cf5c86.png)

**Comment by ghiscoding** [comment]
You can go into the `node_modules/slickgrid/plugins/slick.cellselectionmodel.js` and on line 48 remove the line with `_selector = null;` which I added but I'm not sure why it does that though, that is in the destroy so it should be ok

**Comment by ghiscoding** [comment]
Can you actually try to replace the `_selector = null` with the following
```js
if (_selector && _selector.destroy) {
  _selector.destroy();
}
```

**Comment by tannenbaums** [comment]
That fixes that error, ty. I tested it in my app and unfortunately it's still a problem. I can see that the detached element count is much lower, but at the same time the DOM Nodes count is still growing very fast, like it used to. So it seems like it's not just detached nodes that's the problem.. 
Agagin: If I set disable filter on both pages that I toggle between (and they both contain the grid) MY APP IS WORKING PERFECTLY FINE!!!

**Comment by ghiscoding** [comment]
I've already spent too much time on this, I can't go further than that. It should be much lower and you should also wait few seconds before it goes down. If you do a heap recording you'll see it has a lot less detached div/span. Also what I find strange is that the count of detached elements goes down as soon as you click the "record heap" button, not sure why it does that. 

I'm out of idea and out of time, if that doesn't work for you well it's sad but that would be your turn to help... and seriously your App should become more responsive now, I've fixed a lot of those detached elements/events. Flatpickr (date picker) was a big one too

**Comment by ghiscoding** [comment]
@tannenbaums 
I think I have found probably the biggest issue/leak, it seems that Angular-Slickgrid component doesn't get fully destroyed and stays in memory and when that happens it keeps the entire dataset of the previous grid and it keeps adding up over and over...that is bad, very bad, so now I nullifying a few of these lib variable on the destroy
```ts
    this._dataset = null;
    this.datasetHierarchical = null;
    this._columnDefinitions = [];
    this.gridOptions = undefined;
    this._angularGridInstances = null;
```
So how did I find that? I looked a bit more at the [article](https://web.dev/detached-window-memory-leaks/) that I referenced earlier and I noticed they were sorting by the biggest leak and in our case it's `(string)` and I saw it kept growing while switching page, then I started to inspect and saw that all the grid data was still in there even though I was not longer on a page with slickgrid (oh so bad). 

![image](https://user-images.githubusercontent.com/643976/98613407-3bf86100-22c4-11eb-87fe-927f8ed11b3a.png)

Now with the nullifying it doesn't grow exponentially anymore. 
If you had huge dataset between each page, and in the case of Angular-Slickgrid Examples it's all random data so it cannot cache the result, it can grow quite large.

So give this new set a try
[slickgrid.zip](https://github.com/ghiscoding/Angular-Slickgrid/files/5514070/slickgrid.zip)
    - `/node_modules/slickgrid/`
[angular-slickgrid-dist.zip](https://github.com/ghiscoding/Angular-Slickgrid/files/5514072/angular-slickgrid-dist.zip)
    - `/node_modules/angular-slickgrid/`

I would expect a huge improvement

**Comment by tannenbaums** [comment]
Sorry I haven't responded, I was swamped with other things that came up... But sadly to say still no go. The problem is very clearly somewhere in filters, is that where the fixes were? (doesn't look like it looking at the commit, but I might be wrong...) 
Look, let me put it this way: The title of this bug may have been wrong, I was assuming that the problem was leaking nodes, but who knows maybe the problem is something else, I can't say. What I could tell you though, is that the issue can be reproduced using the samples (using the latest, I did a fresh download from master today, which I saw that you merged all the fixes into), as follows: if you go to 9 and in the title filter hold down one of the letters let's say d. watch the speed, it goes flawlessly, without getting stuck.
Now: toggle between 9 and 12 40 times then try it again, watch how it gets stuck. Now I know, you might say 40 times is crazy. Well in my app it's after 6 times, but truth to tell, it shouldn't happen even after 40 times, and in a real live app that people use all day long the clicks add up very quickly. If you start again and try the same 40 times by toggling between 1 and 2 and then typing into 9 it's still smooth (you need to restart the browser between each test to know for sure that the heap is starting clean). So there's very clearly an issue with filters (4 and 9 use filters, 1 & 2 don't).

**Comment by ghiscoding** [comment]
Yeah I found out that it's actually Angular which keeps everything in memory, not necessary my lib. However to really clear the dataset, you can use `ngOndDestroy() { this.dataset = null; }` to clear it from the heap before leaving the page. 

I made lot of changes in the lib (not created a PR yet) and also in the Filters and the Filter Service. 

So please give 1 last shot at it, I see some improvement in heap size on my side. 
That is seriously the last time that I work on this, I'm actually not able to reproduce your problem (even with the steps you just wrote), perhaps because my work is barely a year old and it has 32Gb of RAM on Windows 10.

So make sure to replace both content from the 2 files below.

[slickgrid.zip](https://github.com/ghiscoding/Angular-Slickgrid/files/5519932/slickgrid.zip)
   - `/node_modules/slickgrid/`
[angular-slickgrid-dist.zip](https://github.com/ghiscoding/Angular-Slickgrid/files/5520086/angular-slickgrid-dist.zip)
    - `/node_modules/angular-slickgrid/`

NOTE on Filters

Since you also mentioned that you type multiple characters in the filter, I have to say that currently there's just no delay or debounce (wait for user to stop typing) on the text filter, it you type 50 chars, it will execute 50 times the filter callback. I do a debounce on the filters when using backend services but it's not there when using local (in-memory) dataset. I was thinking to do that in the future, but currently it doesn't, so keep that in mind.

**Comment by tannenbaums** [comment]
I'm getting an error:

![image](https://user-images.githubusercontent.com/38888997/98733822-1bd1ac00-236f-11eb-8816-c95c4a0bf141.png)

**Comment by ghiscoding** [comment]
I'm not getting that error but here I made a small change, hopefully that will make it work
[angular-slickgrid-dist.zip](https://github.com/ghiscoding/Angular-Slickgrid/files/5520195/angular-slickgrid-dist.zip)

**Comment by ghiscoding** [comment]
ahh wait I do have that error, give me a minute

**Comment by ghiscoding** [comment]
There you go, should be ok now, error is gone, I nullified a little too much before.
[angular-slickgrid-dist.zip](https://github.com/ghiscoding/Angular-Slickgrid/files/5520231/angular-slickgrid-dist.zip)

**Comment by ghiscoding** [comment]
Small change,
[angular-slickgrid-dist.zip](https://github.com/ghiscoding/Angular-Slickgrid/files/5520313/angular-slickgrid-dist.zip)

**Comment by tannenbaums** [comment]
still no go. Yes it goes down but as you keep on clicking it continues to climb up. I just ran the sample code again (using this morning's version) and after toggling bet. 9 and 12 10 times (20 clicks) node count is up to 21k (after forcing gc)

![image](https://user-images.githubusercontent.com/38888997/98737629-73264b00-2374-11eb-8f41-3353617d6b12.png)

**Comment by ghiscoding** [comment]
I don't think looking at the node count is what really changes much to the responsiveness, I would bet that this node count goes up because Angular keeps everything in memory and doesn't remove them well. I'm more interested in the JS event listener count as I think that is the one we should definitely care about and those are the ones that Filters are using. Have you tried the Filters since then? I would expect them to be more responsive then before. That is as far as I can go.

**Comment by tannenbaums** [comment]
I have tried the latest version and it's the exact same problem. When you merge the changes into master I'll be able to download the latest samples and see if I can repro. But, if you are not able to repro, than it's a problem. Don't know. From where I'm sitting the problem is exactly the same as when we started and it clearly has to do with the filters.

**Comment by ghiscoding** [comment]
I'm not able to reproduce probably because I have plenty of RAM and I would be really surprised if all the changes give you no improvement whatsoever. I mean I do see the node count go up and never back down to its original count but that doesn't change the responsiveness of all the examples on my side.

I can't release a new version because there were few changes made in the core which the PR is still not merged yet and it will probably take few weeks to see a new release on that side (I don't control that one). So the only way to get you going with all these changes were the 2 zips I provided (again you need both to be changed) and if they don't improve the performance at all then I'm sorry but I'm out of idea and out of time (already spent a week in total on this) . I have never seen issues like you mentioned and I never had any other users mentioning this either. I don't know if it's related to memory but it's possible. Nonetheless, I'm 100% that all the changes I have made **must** have some perf boost of some kind, there were a lot of event handlers that weren't properly unsubscribed and cleaned up, so the fact that you keep saying it's the same as when you first open the issue is a little mind blowing. 

Lastly I can't create a PR today anyway because now I have a load of unit tests that are failing because I now nullify a few objects and that makes a few unit tests to fail. Will need to look at that later, at this point the 2 zips I sent you is the only way to get latest changes.

**Comment by tannenbaums** [comment]
I appreciate all your time and effort though, Thank you!!

**Comment by ghiscoding** [comment]
I actually found something that does slowdown the text filter and probably has an impact on your side... Some Filters have multiple events attached to the elements and in some cases it was calling multiple search filtering execution (the input text filter is one of them).

For the full explanation, this [line](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/filters/inputFilter.ts#L88) uses 3 event types `this.$filterElm.on('keyup input change', ...);` and that was too much since for some use case (typing a character was triggering 2 events `input` and `keyup`) hence that is slowing down the filtering process. So you might ask why are there 3 event types anyway, isn't it overkill? The answer is because I have to cover all of the following (and none of the event cover everything):
1. with character typed (keyup)
2. with input spinner, that are the up/down arrows when using a Float Filter
3. with mousewheel, similar to number 2 but using the wheel instead
4. with paste text by mouse command
5. with ENTER key to trigger an automatic filter

After some research and testing some code change, I found out that the `input` will cover 4/5 conditions, however the last condition (with ENTER key) can only be triggered by a `keyup` event and so I modifed that event to only care about the ENTER key. So at the end of it, typing a character now sends only 1 search execution not multiple.

I only worked on a fix for my other lib, Slickgrid-Universal in this [commit](https://github.com/ghiscoding/slickgrid-universal/pull/156/commits/3b9ae2441520d7ea0c3ac4735fc2d1daa2cfcd09). I should be able to port this to Angular-Slickgrid in coming days and provide you another build/dist to try if you wish.

**Comment by tannenbaums** [comment]
Yes please, would be greatly appreciated! Can you give me a zip file by any chance?

**Comment by ghiscoding** [comment]
Yes I'll do a zip when I have time to update the code in Angular-Slickgrid, it should be by the end of this week. 
At this point the zip is all we have to test, since the core lib PR is still waiting to be merged and released.

Thanks for the feedback.

BTW, how big is your dataset (rows) and how many columns do you have? Also, is that slowness only on the input text filter or is it also slow on other type of filters like singleSelect or compoundDate? Basically, that would help to pinpoint if it's only the input text filter being the problem

**Comment by tannenbaums** [comment]
I was using the filter text as an example. The actually problem in my app is not in the filter, but rather we have a bunch of input boxes, such as comments, notes etc. not in the grid but somewhere else on the page. They are all slow! If I turn the filters off they are fast!!! that's the key point here, that something in filters is causing the input in the entire app to slow down!
As far what we have:
We have a couple of pages with grids. One of them has 10 columns and rows: well we use paging, so it's 100 rows per page and about 500 pages.
And the other has 6 columns and let's say 12k rows

**Comment by ghiscoding** [comment]
500 is a lot of pages...

> The actual problem in my app is not in the filter, but rather we have a bunch of input boxes, such as comments, notes etc. not in the grid but somewhere else on the page. They are all slow!

I wonder if your input boxes are actually conflicting with the filters in the grid, the Filters are using their own events and always adding event listener only to the filter elements (basically the Filters event shouldn't pollute outside elements) but I wonder if your input might pick up the filters from the grid. For example do you have an Angular directives that might be watching events on all inputs that would conflict with the grid filter inputs? Where I'm getting at is that you are the only person who mention some slowness and I created the lib 3 years and have over 300 users of the lib. So I'm wondering if some of your stuff on the page is somehow conflicting. However you kinda said that it's reproducible on the github demo page...hmm

**Comment by tannenbaums** [comment]
I'm taking a look. I'm working on removing as many irrelevant parts out of the app and see if it's still a problem. It might take some time...

**Comment by tannenbaums** [comment]
I believe I finally found the culprit, it's flatpickr.js!!! When the Angular-Slickgrid filters are on, it listens to the onKeyDown event and gets executed on every key stroke no wonder why the pain :)  (I verified, this only gets called when the filters are on)

![image](https://user-images.githubusercontent.com/38888997/99043855-d96dc200-255c-11eb-8c5d-d0b9c3264f9e.png)

Please let me know what you think...

**Comment by ghiscoding** [comment]
oh wow why would Flatpickr listen to key stroke?? We don't even need that since the input is read only and is only used as a clickable input in Angular-Slickgrid, that is bad. It also has a memory leak, which I mentioned earlier, and I believe that I put in a patch (in current PR, not released but it's in the last zip) to stops the leak when destroying the component but perhaps it's not bulletproof. Looking at the code of Flatpickr and searching for the `keyDown` event and yes the event is bound to `window.body` [here](https://github.com/flatpickr/flatpickr/blob/master/src/index.ts#L419), this is **bad** since any element will automatically pass through Flatpickr event regardless if it's a Flatpickr element or not... bad, bad, bad!!!

Looking at Flatpickr issues, I found these 2 (issue [#1387](https://github.com/flatpickr/flatpickr/issues/1387) and [#1444](https://github.com/flatpickr/flatpickr/issues/1444) are relevent to your problem. Looking even more at the code and I see a bunch of other events that are attached to `window.document` and doesn't really check if the element that sends the event is really related to Flatpickr. Now I'm starting to reconsider the choice of external date picker lib.

Have you tried to not use any filter with Flatpickr (compoundDate & dateRange)? For example use only the input text default filter, does that still make the page slow?

**Comment by tannenbaums** [comment]
I commented out this line of code from flatpickr

            `bind(window.document.body, "keydown", onKeyDown);`

and now it's flying. The date filters are still working, but now I cannot remove the filter. I hit the backspace to remove, but nothing happens...

**Comment by tannenbaums** [comment]
any way you can add a clear button on the date inputs?

**Comment by ghiscoding** [comment]
I only added recently a clear date on the Date Editor but I don't want to a add a clear date for the filters...why? Because **all** Filters have a "Clear Filter" in the header menu, so there's no reason to duplicate all the code for no real benefit. I actually didn't even know we could do backspace on the Flatpickr input, I thought you couldn't because it was read only, seriously it's strange (perhaps bad UX?) that it works.

![image](https://user-images.githubusercontent.com/643976/99087185-7a2da300-2598-11eb-8b9f-4d474d7108db.png)

**Comment by ghiscoding** [comment]
BTW, I'm really glad you found the issue, it's a bit of a relief (even though sad) that it's not directly Angular-Slickgrid. Welcome to the Open Source world were multiple libs depend on multiple dependencies to make greater libs 🤣 

Anywho, I did fix multiple unsubscribed events and detached elements, so we'll take that as a bonus lol.

**Comment by tannenbaums** [comment]
exactly, was going to say the same thing, I guess it was a worthy cause, but boy this was nightmare, but I'm glad it's over. Thank you so much again for all your help and support. When are we expect the new version?

**Comment by tannenbaums** [comment]
By the way, so does it make sense to you that I can just keep that line commented out for now? Like, doesn't look like I'm losing any functionality. Does that make sense to you?

**Comment by tannenbaums** [comment]
also: yes I totally forgot about those little buttons in each column for some reason it wasn't showing up in our app, some styling issue.

**Comment by ghiscoding** [comment]
Commenting out the line is most probably the best you can do to avoid having the issue on your side, however that will be wiped out every time you do a `npm install` to get latest versions of any packages. That is something I had to do for a while myself, funny enough it was also Flatpickr causing other issues which was that other PR I talked about. The best way I had to deal with this was to keep the file opened in Notepad++ (which is always open on my computer) and after running `npm install` then Notepad++ detect changes and would ask me "New Changes detected Reload?" and I would answer "No" and click then click on Save to resave it.

It might be good to a PR on the Flatpickr project to add a flag to disable that `keyDown` binding, personally I would disable it when using the `allowInput: false` but this might conflict with user who still expect the backspace to work like you said earlier... so a new flag might be required. 

Next release will probably be next week.
I also sent a message to the 6pac/SlickGrid author on his project, so that would be nice to have it included as well. I fixed a few more unsubscribed events yesterday as well on that same PR I had opened. 

> also: yes I totally forgot about those little buttons in each column for some reason it wasn't showing up in our app, some styling issue.

You could also make the menu showing at all time, I did that in the Salesforce Theme which you can see on the [Slickgrid-Universal Demo](https://ghiscoding.github.io/slickgrid-universal/#/example01), however it does take same space and the business actually asked me to turned that off and put back the menu only showing on hovering. So it's up to you, the SASS variable for that is `$header-menu-display` which you can set to `inline-block` to make it showing at all time.

**Comment by tannenbaums** [comment]
Interesting! Ok thank you for the info, I think we are fine with the hovering, but I'll keep it in mind! Thank you so much, I'm just so excited and feel so relieved. :smiley:  Bless the almighty!!!

**Comment by ghiscoding** [comment]
I'm also excited to leave that behind us 😉

**Comment by ghiscoding** [comment]
@tannenbaums 
I created a PR [#2326](https://github.com/flatpickr/flatpickr/pull/2326) on the Flatpickr project to add a flag `disableKeyDownBinding` that will do what you did manually. The real fix to Flatpickr would be to disregard anything unrelated to Flatpickr but I don't fully understand how to do that, so just disabling the keydown listener should suffice for now. 

BTW, just by adding a console.log to test this out, I found out that it adds a keydown listener to each and every Flatpickr inputs created on the page, the more Flatpickr inputs you have, the slower your page becomes... the more reason to disable the binding. 

The code I added in the Flatpickr lib is mainly this piece
```js
if(!self.config.disableKeyDownBinding)
  bind(window.document.body, "keydown", onKeyDown);
```

**Comment by tannenbaums** [comment]
that's great! Actually I played with it a bit more and noticed that uncommenting the bind does not bring back the backspace, not sure when that broke but seems unrelated to this.

Also: I think that instead of commenting it out, it's enough to just modify it to this:
            bind(self._input, "keydown", onKeyDown);
so now the event will still fire but only on the control itself.

**Comment by ghiscoding** [comment]
> Also: I think that instead of commenting it out, it's enough to just modify it to this:
> bind(self._input, "keydown", onKeyDown);

It was mentioned in that Flatpickr [issue #1387](https://github.com/flatpickr/flatpickr/issues/1387) but the author decided to keep the event on the `window`. I'm not totally sure why he did that but perhaps there are some key stroke that might be outside of the picker? For if you do that, does the arrow keys still work in the picker (I never use them but you can use arrow keys to change date once the picker is open), there's also that extra time picker that comes up optionally and that also might not work if it's outside the picker? I don't know but I find that odd that a date picker would be watching every key stroke in the entire page (window), that is bad practice. I did something similar with the `multiple-select.js` with the click event bound to the `body` but I make sure the element is a multiple-select element before doing anything. 

So anyway, I think disabling the Flatpickr `onKeyDown` might be the easiest to get rid of these issues you had. Though I know it will take couple months before any versions is released on that lib, that is if my PR even gets merged, we'll see.

**Comment by tannenbaums** [comment]
Yes, the arrow keys still work!!

Also: "I did something similar with the multiple-select.js with the click event bound to the body but I make sure the element is a multiple-select element before doing anything."

just fyi, even if you have an empty even handler, the application will slow down drastically just by having an even fire on every keystroke on the page....before I commented out the bind, if first commented out the code in the handler and it didn't make a difference. only when I disabled the listener completely, I saw a major improvement...

**Comment by ghiscoding** [comment]
that's good to know, which makes another point to why did the Flatpickr author used the `window.body` to add the `keydown` listener. I again think this will take quite some time for this to be resolved in that lib, so your best option is to keep commenting out the necessary line or modify it... however note that this won't work when using a CI/CD flow (continuous integration), if that is what you use to build your Prod build, then you won't be in much better position, but anyway that is for you to look into that until a valid solution is merged and released in the Flatpickr project.

**Comment by tannenbaums** [comment]
oh that's great news (the release of a new version)...no I'm not using CI here, so it's ok.
And I have a correction to make: my co-worker reminded me that the backspace only works while the date picker is showing. so I ran another test and sure enough if I comment out the bind, the backspace doesn't work at all, but if I bind it to self._input i'm still able to clear it that way...so I'm going to keep it that way for now...

**Comment by tannenbaums** [comment]
Truth to be told, I'm still not so ok, still slow on input, it just takes more clicks now for the problem to show up. But here's another thing I noticed, not sure if it's coming from slick-grid or Angular-Slickgrid, but it's constantly firing because it's on a timer. And it seems to effects performance:
Any way to turn that off without turning the whole auto size feature. Obviously I want auto size, but is there a way to trigger it when something changes in the grid and not on a constant basis?

![image](https://user-images.githubusercontent.com/38888997/99324382-175f3480-2842-11eb-84dc-483a8bb976f2.png)

**Comment by ghiscoding** [comment]
It's not on a constant basis, it's only on a window resize and by the first page initialization, It's also on a `setTimeout` only when using a resize delay (by default it's 10ms after a page load then 0ms after that). There's no way to turn that off except by disabling the auto-resize. I seriously doubt there's any issue with the Resizer Service, your page must be triggering a resize somehow. 

You're way out of subject from the original issue, sorry but I can't always help you every time, you'll have to dig in to find what causes the resize on your side. Typically you can expect 1 or 2 resizes when going on a page, one from the page first load and maybe another one after that but it should stop after unless the window resize kicks in and for that I've also put an event namespace with jQuery to avoid having multiple grids conflicting with each other but if 1 grid changes the window size then it might call a grid(s) resize.
`$(window).on(`resize.grid.${this._gridUid}`, () => this.handleResizeGrid()`

or you can pause the resizer, there's a demo on [Example 2](https://ghiscoding.github.io/Angular-Slickgrid/#/formatter), click that "Pause auto-resize" button to stop/resume it.

**Comment by tannenbaums** [comment]
I thought it was constantly firing, I see now it's only when hovering over the grid. Sorry about that!!

**Comment by ghiscoding** [comment]
> Also: I think that instead of commenting it out, it's enough to just modify it to this:
> bind(self._input, "keydown", onKeyDown);
> so now the event will still fire but only on the control itself. But I have no idea how to test it...

The code change you mentioned is not enough, I created another [PR #2329](https://github.com/flatpickr/flatpickr/pull/2329) (and closed previous one) on the Flatpickr project to properly address the Flatpickr event handling. The `bind(self._input, "keydown", onKeyDown);` event is not enough since that will only listen to the input but you also need to listen to the event on the date picker (the date container/picker) itself (for example the code you had will make Esc/Backspace work but you won't be able to use the Arrow Keys to change date inside the picker) and the new [PR #2329](https://github.com/flatpickr/flatpickr/pull/2329) I created does fix that, so you probably want to update your local code of Flatpickr. 

Let's hope my PR gets merged eventually 🤞

**Comment by ghiscoding** [comment]
All the fixes that I've done in the core and Angular-Slickgrid and other features are now released under the new version `2.23.1`, see [release 2.23.1](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.23.1)

**Comment by tannenbaums** [comment]
That's great tysm!! and yes exactly, although I'm still finding more libs that do the same thing, such as jquery, but I'm still in the middle of analyzing that...

**Comment by tannenbaums** [comment]
take a look at this code below... and since the angular-slickgrid is in memory 30 times (after clicking 30 times) this happens that many times, when I remove it I'm good to go even after 30 times:

   hookUndoShortcutKey() {
        document.addEventListener('keydown', (e) => {
            const keyCode = e.keyCode || e.code;
            if (keyCode === 90 && (e.ctrlKey || e.metaKey)) {
                if (e.shiftKey) {
                    this._undoRedoBuffer.redo(); // Ctrl + Shift + Z
                }
                else {
                    this._undoRedoBuffer.undo(); // Ctrl + Z
                }
            }
        });
    }

**Comment by ghiscoding** [comment]
I don't think I can change that one, it has to be on the document since you can do a redo/undo from anywhere. I don't understand why your system is slowing down with a `keydown` listener, seriously that kind of listener is quite common. I understand that for Flatpickr it should never be listening on the `document.body` but to listen for Redo/Undo shortcut I think it's fair to leave that on the `document.body` and we can't put that on the grid element since that would require the user to focus on the grid which won't work most of the time... the best option for you is to disable the cell external copy feature.

**Comment by tannenbaums** [comment]
there's nothing wrong with that, everyone else seem to be doing it too...but coupled with a memory leak, not a good combination...but np I'll just disable it, didn't realized it was tide to that option...

**Comment by ghiscoding** [comment]
By default it's not enabled, the `excelCopyBufferOptions` is not in the globals and you can see which controls/plugins is enabled by looking at the [global-grid-options](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/global-grid-options.ts) which are mentioned in this [Global Options - Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Global-Options)

Also, you keep saying memory leak but I don't think that is true anymore, I mean apart from the leak caused by Flatpickr, I have put a lot of effort addressing most of the unsubscribed events and detached elements when destroying. Only Flatpickr remains, which you can fix manually until that PR is merged (hopefully). I'd like to close this subject.

**Comment by tannenbaums** [comment]
Someone needs me now, so I'll work on it later, but if you go to the demo site and toggle the examples let's say 30 times and take a hip snapshot you'll see that angular-slickgrid is there many times...put a breakpoint in the code above and you'll see it runs many times...I'm pretty sure that's the case, but I'll check it out later...

**Comment by tannenbaums** [comment]
yup I just confirmed that. I forgot one step: after toggling many times and setting the breakpoint, go to example 4 and start typing into one of the column filters, and watch how many times the handler is running...(as many as there are instances in the heap), the more you toggle the more times this will be called.

![image](https://user-images.githubusercontent.com/38888997/99594467-389a5f00-29c1-11eb-9386-274de40610d9.png)

**Comment by ghiscoding** [comment]
Ok I think I know what the issue is, all the SlickGrid external plugins, like this cell copy manager is, have to be registered/loaded via `registerPlugin()` but I forgot to use the `unregisterPlugin()` when destroying all of these plugins. I need to add a `dispose` to loop through all loaded plugins in the `ExtensionService` and call that `unregisterPlugin()` on each.

Can you open another issue with the last comment you wrote. This issue is getting way too long and there's something already pushed and released.

**Comment by tannenbaums** [comment]
bug submitted

**Comment by tannenbaums** [comment]
quick question: I just got the latest release 2.23.1 and now i see my components are multiple time in the heap. if I overwrite the slickgrid pkg with the last slickgrid.zip in this thread (angular-slickgrid i don't need to touch, just slickgrid), all is good again... any ideas?

**Comment by ghiscoding** [comment]
No I don't know and not to be rude but I'd really like to close this subject once and for all and forget it after finishing that other upcoming PR. I'm alone working on this lib and that sucked up a lot of my time 🙄

**Comment by tannenbaums** [comment]
it seems obvious that the slickgrid version that you included in the official release has something that's causing a leak again...if you stick to the version in the zip you are better off...but up to you...i'll just have to stick to the zip version...

**Comment by ghiscoding** [comment]
if that is so obvious to you then why aren't you helping in pinpointing the issue and contribute some code? 

Don't take me wrong, the fact that you found all these unsubscribed events is really great and beneficial to the library (and I believe I fixed them all except for Flatpickr) and of course I do want to fix every leaks but now you keep complaining about the heap size and that tells me... **nothing** 

If you could provide something concrete that would be more helpful, because I just can't compare from the zip. If you tell me "Hey this thing is leaking and here's the reason" (like you did with the `onKeyDown` yesterday) then great I can fix it but when you just say "There's another leak" that's not helpful at all and it's more frustrating than anything else for both you and me.

Perhaps you could review all the PRs that I've made related to those leaks that you keep talking about (PRs #626, #627, #628, #629), it's probable around #628 or #630

As a reminder, I am not paid for supporting and providing this lib, that is the world of Open Source

**Comment by tannenbaums** [comment]
I hear you and I appreciate your being open with me, and I'm sorry for saying it's obvious. I thought it'll be easy for you to tell where the problem is, since you just made the changes...but i guess not. it's a shame because we already had it, and now it seemed to have disappeared. oh well...
as far is reproducing the issue, i mean it's the same idea if you put a breakpoint into any event handler like key down you should see it firing as many times as there are instances... but it's possible that your fixes to the new bug will fix this also...

**Comment by ghiscoding** [comment]
You might have forgot that if you just ran an npm install (which you just did since you just installed latest version), that will wipe out all the changes you've done on Flatpickr and you need to re-apply the changes to fix that keydown event leaking.

**Comment by tannenbaums** [comment]
my changes are there I verified. It's the slickgrid...
