### ISSUE TITLE
How to make column string filter case insensitive?

### ISSUE THREAD

**Issue by ctung** [ghiscoding/Angular-Slickgrid#9]
I couldn't find any documentation on how to write custom filters for the header row filters.
I'm trying to make the string filter case-insensitive.
I know the column has a "filter" option, but I'm not sure what to put there.

I see the filter interface:
export declare type Filter = (searchTerm: string, columnDef: Column) => string;

And I see the example:
{ id: 'effort-driven', name: 'Effort Driven', field: 'effortDriven', maxWidth: 80, formatter: Formatters.checkmark,
        type: FieldType.boolean,
        sortable: true,
        filterable: true,
        filter: {
          searchTerm: '', // default selection
          type: FormElementType.select,
          selectOptions: [ { value: '', label: '' }, { value: true, label: 'true' }, { value: false, label: 'false' } ]
        }

but I'm not sure what a case insensitive filter should look like?

**Comment by ghiscoding** [comment]
Good point, I am not supporting custom filter yet (hence why there's no doc about it). I was planning to do that in the future but don't know when (if ever) that will happen. 

On the other hand, I thought it was already case insensitive but after testing it on the [demo site](https://ghiscoding.github.io/Angular-Slickgrid/#/clientside), it does seem to be sensitive to the casing. I probably have to do some tweaking in the [string filter condition](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/filter-conditions/stringFilterCondition.ts).

I should have a fix for case insensitivity by the end of the week, stay tuned. 

For reference and for you info
The structure I went, is to first create [HTML Filter Template](https://github.com/ghiscoding/Angular-Slickgrid/tree/master/src/app/modules/angular-slickgrid/filter-templates), there's currently only 2 (input text, select dropdown) and I'd like to add more in the future. Then depending on what Column Definition Type you use (e.g. `type: FieldType.string`) it will use the appropriate [Filter Condition](https://github.com/ghiscoding/Angular-Slickgrid/tree/master/src/app/modules/angular-slickgrid/filter-conditions). So when setting a Type String, it will use the [String Filter](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/filter-conditions/stringFilterCondition.ts) which is the same filter used regardless of the filter template (input/select/...). If my WiKis are not clear enough, I would certainly welcome PR to update them :)

**Comment by ghiscoding** [comment]
Fixed in new [version 0.8.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v0.8.0) ended being huge, there's a lot of everything (fixes, new features, lot of refactoring). You should look at the list of [changes](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v0.8.0)

**Comment by ctung** [comment]
Thanks for the fix, but after upgrading from 0.6.7 to 0.8.0, I now see the following error:
ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[SlickPaginationComponent -> TranslateService]: 
  StaticInjectorError(Platform: core)[SlickPaginationComponent -> TranslateService]: 
    NullInjectorError: No provider for TranslateService!
Error: StaticInjectorError(AppModule)[SlickPaginationComponent -> TranslateService]: 
  StaticInjectorError(Platform: core)[SlickPaginationComponent -> TranslateService]: 
    NullInjectorError: No provider for TranslateService!
    at _NullInjector.get (core.js:994)
    at resolveToken (core.js:1292)
    at tryResolveToken (core.js:1234)
    at StaticInjector.get (core.js:1102)
    at resolveToken (core.js:1292)
    at tryResolveToken (core.js:1234)
    at StaticInjector.get (core.js:1102)
    at resolveNgModuleDep (core.js:10837)
    at _createClass (core.js:10874)
    at _createProviderInstance$1 (core.js:10848)
    at _NullInjector.get (core.js:994)
    at resolveToken (core.js:1292)
    at tryResolveToken (core.js:1234)
    at StaticInjector.get (core.js:1102)
    at resolveToken (core.js:1292)
    at tryResolveToken (core.js:1234)
    at StaticInjector.get (core.js:1102)
    at resolveNgModuleDep (core.js:10837)
    at _createClass (core.js:10874)
    at _createProviderInstance$1 (core.js:10848)
    at resolvePromise (zone.js:809)
    at resolvePromise (zone.js:775)
    at eval (zone.js:858)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4724)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
    at <anonymous>
defaultErrorLogger @ core.js:1440
ErrorHandler.handleError @ core.js:1501
next @ core.js:5481
schedulerFn @ core.js:4319
SafeSubscriber.__tryOrUnsub @ Subscriber.js:240
SafeSubscriber.next @ Subscriber.js:187
Subscriber._next @ Subscriber.js:128
Subscriber.next @ Subscriber.js:92
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4299
(anonymous) @ core.js:4755
ZoneDelegate.invoke @ zone.js:388
Zone.run @ zone.js:138
NgZone.runOutsideAngular @ core.js:4681
onHandleError @ core.js:4755
ZoneDelegate.handleError @ zone.js:392
Zone.runGuarded @ zone.js:154
_loop_1 @ zone.js:684
api.microtaskDrainDone @ zone.js:693
drainMicroTaskQueue @ zone.js:602
Promise.then (async)
scheduleMicroTask @ zone.js:578
ZoneDelegate.scheduleTask @ zone.js:410
Zone.scheduleTask @ zone.js:232
Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:856
ZoneAwarePromise.then @ zone.js:946
PlatformRef.bootstrapModule @ core.js:5552
(anonymous) @ main.ts:11
../../../../../src/main.ts @ main.bundle.js:272
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:294
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1

**Comment by ghiscoding** [comment]
I don't have that problem but my co-worker does, could you open another issue as this is a new problem.

**Comment by ghiscoding** [comment]
@ctung I think that I found and fixed the error you saw in the console
```bash
SlickPaginationComponent -> TranslateService]:
NullInjectorError: No provider for TranslateService!
```
Could you try latest version [0.8.1](https://www.npmjs.com/package/angular-slickgrid) and report back if this fixes it please. Thanks

**Comment by ctung** [comment]
tested with 0.8.1 and still have the error.  Opened it as a new issue.  Thanks!
